
export interface DataModel {
  id: string,
  category: any[],
  subCategory: string,
  edmFieldName: string,
  edmFieldComponent: string,
  edmFieldExportName: string,
  edmFieldDefinition: string,
  edmFieldNormalizationLength: string,
  edmFieldDerivationLength: string,
  edmFieldSpecificationLength: string,
  scdFieldTranslationLength: string,
  scdFieldFormulaLength: string,
  scdFieldSpecificationLength: string,
  edmFieldMandatory: string,
  isCustom: string,
  vendorName: string,
  vendorFieldName: string,
  scdFieldName: string,
  scdModelName: string,
  scdFieldDefinition: string,
  scdFieldMandatory: string,
  cost: number
}
